routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Frontend\LandingsController::class, 'index'])->name('landing.home');
Route::get('/pengurus', [App\Http\Controllers\Frontend\PengurusController::class, 'index'])->name('pengurus.index');

//PROKER
Route::get('/program-kerja/{departemen}', [App\Http\Controllers\Frontend\ProgramKerjasController::class, 'index'])->name('proker.index');

//GALLERY
Route::get('/gallery-himatifa', [App\Http\Controllers\Frontend\GalleryController::class, 'index'])->name('galleryhima.index');

//? CALENDAR
Route::get('/calendar-himatifa', [App\Http\Controllers\Frontend\CalendarHimaController::class, 'index'])->name('calendarhima.index');

//* BERITA
Route::get('/berita-himatifa', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'index'])->name('beritahima.index');
Route::get('/berita-himatifa/{category}', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'showkategori'])->name('kategori.beritahima');
Route::get('/berita-himatifa/detail/{slug}', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'show'])->name('beritahima.show');

//!CONTACT US
Route::get('/contact-us/deteksi-kesalahan-ketik', [App\Http\Controllers\ContactusController::class, 'pendaftaran'])->name('pendaftaran.hima');
Route::post('/contact-us/deteksi-kesalahan-ketik/hasil', [App\Http\Controllers\ContactusController::class, 'jarowinkler'])->name('jaro.distance.hima');
Route::post('/contact-us/deteksi-kesalahan-ketik/pdf-text', [App\Http\Controllers\ContactusController::class, 'pdftext'])->name('pdf-text.store');
Route::post('/contact-us/kritik-saran/store', [App\Http\Controllers\ContactusController::class, 'store_kritiksaran'])->name('kritiksaran.store');

Auth::routes();


Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('admin.dashboard');
    Route::resource('roles', App\Http\Controllers\Backend\RolesController::class);
    Route::get('/update-profile', [App\Http\Controllers\Backend\UpdateProfileController::class, 'index'])->name('update-profile.index');
    Route::post('/update-profile/update', [App\Http\Controllers\Backend\UpdateProfileController::class, 'update'])->name('update-profile.update');
    Route::resource('users', App\Http\Controllers\Backend\UsersController::class);
    Route::resource('sliders', App\Http\Controllers\Backend\SlidersController::class);

    // Pengurus
    Route::resource('pengurus/visimisi', App\Http\Controllers\Backend\Anggota\VisimisiController::class);

    // KAHIMA WAKAHIMA
    Route::get('/pengurus/bph', [App\Http\Controllers\Backend\Anggota\BphController::class, 'index'])->name('bph.index');
    Route::get('/pengurus/bph/create', [App\Http\Controllers\Backend\Anggota\BphController::class, 'create'])->name('bph.create');
    Route::post('/pengurus/bph/store', [App\Http\Controllers\Backend\Anggota\BphController::class, 'store'])->name('bph.store');
    Route::get('/pengurus/bph/edit/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'edit'])->name('bph.edit');
    Route::post('/pengurus/bph/update/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'update'])->name('bph.update');
    Route::delete('/pengurus/bph/delete/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'destroy'])->name('bph.destroy');

    // SEKRETARIS BENDAHARA
    Route::get('/pengurus/bph/createsb', [App\Http\Controllers\Backend\Anggota\BphController::class, 'createsb'])->name('bph.createsb');
    Route::post('/pengurus/bph/storesb', [App\Http\Controllers\Backend\Anggota\BphController::class, 'storesb'])->name('bph.storesb');
    Route::get('/pengurus/bph/editsb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'editsb'])->name('bph.editsb');
    Route::post('/pengurus/bph/updatesb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'updatesb'])->name('bph.updatesb');
    Route::delete('/pengurus/bph/deletesb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'destroysb'])->name('bph.destroysb');

    // ANGGOTA
    Route::resource('pengurus/anggota', App\Http\Controllers\Backend\Anggota\AnggotaController::class);
    Route::resource('pengurus/departemen', App\Http\Controllers\Backend\Anggota\DepartemenController::class);

    Route::resource('pengurus/deskbph', App\Http\Controllers\Backend\Anggota\DeskripsiBPHController::class);
    Route::resource('pengurus/deskanggota', App\Http\Controllers\Backend\Anggota\DeskripsiAnggotaController::class);

    //Gallery
    Route::get('/gallery', [App\Http\Controllers\Backend\GallerysController::class, 'index'])->name('gallery.index');
    Route::get('/gallery/create', [App\Http\Controllers\Backend\GallerysController::class, 'create'])->name('gallery.create');
    Route::post('/gallery/store', [App\Http\Controllers\Backend\GallerysController::class, 'store'])->name('gallery.store');
    Route::get('/gallery/edit/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'edit'])->name('gallery.edit');
    Route::post('/gallery/update/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'update'])->name('gallery.update');
    Route::delete('/gallery/delete/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'destroy'])->name('gallery.destroy');

    Route::get('/category/create', [App\Http\Controllers\Backend\GallerysController::class, 'createcat'])->name('category.create');
    Route::post('/category/store', [App\Http\Controllers\Backend\GallerysController::class, 'storecat'])->name('category.store');
    Route::get('/category/edit/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'editcat'])->name('category.edit');
    Route::post('/category/update/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'updatecat'])->name('category.update');
    Route::delete('/category/delete/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'destroycat'])->name('category.destroy');


    //Calendar
    Route::resource('calendar/manage-calendar', App\Http\Controllers\Backend\CalendarsController::class);

    //!BERITA
    Route::get('/berita/manage-berita', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'index'])->name('manage-berita.index');
    Route::get('/berita/manage-berita/create', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'create'])->name('manage-berita.create');
    Route::post('/berita/manage-berita/store', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'store'])->name('manage-berita.store');
    Route::get('/berita/manage-berita/edit/{slug}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'edit'])->name('manage-berita.edit');
    Route::post('/berita/manage-berita/update/{id}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'update'])->name('manage-berita.update');
    Route::delete('/berita/manage-berita/destroy/{id}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'destroy'])->name('manage-berita.destroy');
    Route::get('/berita/manage-berita/slug', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'slug'])->name('manage-berita.check-slug');


    Route::resource('berita/category-berita', App\Http\Controllers\Backend\Berita\CategoryBeritasController::class);

    //*CONTACT US
    Route::resource('/contact-us-admin', App\Http\Controllers\Backend\ContactUsAdminController::class);

    //! POPOSAL KEGIATAN
    Route::get('/ajuan-proposal-kegiatan', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexhima'])->name('proposal.indexhima');
    Route::get('/ajuan-proposal-kegiatan/prodi', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexprodi'])->name('proposal.indexprodi');
    Route::delete('/ajuan-proposal-kegiatan/destroy/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'destroy'])->name('proposal.destroy');
    Route::get('/ajuan-proposal-kegiatan/fakultas', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexfakultas'])->name('proposal.indexfakultas');
    Route::get('/ajuan-proposal-kegiatan/editprodi/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'editprodi'])->name('proposal.editprodi');
    Route::get('/ajuan-proposal-kegiatan/editfakultas/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'editfakultas'])->name('proposal.editfakultas');
    Route::post('/ajuan-proposal-kegiatan/updateprodi/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'updateprodi'])->name('proposal.updateprodi');
    Route::post('/ajuan-proposal-kegiatan/updatefakultas/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'updatefakultas'])->name('proposal.updatefakultas');
    Route::post('/ajuan-proposal-kegiatan/store-proposal', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'store'])->name('proposal.store');
    Route::get('/ajuan-proposal-kegiatan/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'show'])->name('proposal.show');
    Route::get('/download-proposal-kegiatan/{file_name}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'downloadprop'])->name('proposal.download');

    //? Deteksi KESALAHAN KETIK
    Route::get('/deteksi-kesalahan-ketik', [App\Http\Controllers\Backend\TipografiCheckController::class, 'index'])->name('tipografi.index');

resources/views/superadmin/layouts/customizer.blade.php
<aside class="customizer">
    <a href="javascript:void(0)" class="service-panel-toggle"><i class="fa fa-spin fa-cog"></i></a>
    <div class="customizer-body">
        <ul class="nav customizer-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true"><i class="mdi mdi-wrench font-20"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#chat" role="tab" aria-controls="chat" aria-selected="false"><i class="mdi mdi-message-reply font-20"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false"><i class="mdi mdi-star-circle font-20"></i></a>
            </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
            <!-- Tab 1 -->
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                <div class="p-15 border-bottom">
                    <!-- Sidebar -->
                    <h5 class="font-medium m-b-10 m-t-10">Layout Settings</h5>
                    <div class="custom-control custom-checkbox m-t-10">
                        <input type="checkbox" class="custom-control-input" name="theme-view" id="theme-view">
                        <label class="custom-control-label" for="theme-view">Dark Theme</label>
                    </div>
                    <div class="custom-control custom-checkbox m-t-10">
                        <input type="checkbox" class="custom-control-input sidebartoggler" name="collapssidebar" id="collapssidebar">
                        <label class="custom-control-label" for="collapssidebar">Collapse Sidebar</label>
                    </div>
                    <div class="custom-control custom-checkbox m-t-10">
                        <input type="checkbox" class="custom-control-input" name="sidebar-position" id="sidebar-position">
                        <label class="custom-control-label" for="sidebar-position">Fixed Sidebar</label>
                    </div>
                    <div class="custom-control custom-checkbox m-t-10">
                        <input type="checkbox" class="custom-control-input" name="header-position" id="header-position">
                        <label class="custom-control-label" for="header-position">Fixed Header</label>
                    </div>
                    <div class="custom-control custom-checkbox m-t-10">
                        <input type="checkbox" class="custom-control-input" name="boxed-layout" id="boxed-layout">
                        <label class="custom-control-label" for="boxed-layout">Boxed Layout</label>
                    </div>
                </div>
                <div class="p-15 border-bottom">
                    <!-- Logo BG -->
                    <h5 class="font-medium m-b-10 m-t-10">Logo Backgrounds</h5>
                    <ul class="theme-color">
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin1"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin2"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin3"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin4"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin5"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-logobg="skin6"></a></li>
                    </ul>
                    <!-- Logo BG -->
                </div>
                <div class="p-15 border-bottom">
                    <!-- Navbar BG -->
                    <h5 class="font-medium m-b-10 m-t-10">Navbar Backgrounds</h5>
                    <ul class="theme-color">
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin1"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin2"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin3"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin4"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin5"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-navbarbg="skin6"></a></li>
                    </ul>
                    <!-- Navbar BG -->
                </div>
                <div class="p-15 border-bottom">
                    <!-- Logo BG -->
                    <h5 class="font-medium m-b-10 m-t-10">Sidebar Backgrounds</h5>
                    <ul class="theme-color">
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin1"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin2"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin3"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin4"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin5"></a></li>
                        <li class="theme-item"><a href="javascript:void(0)" class="theme-link" data-sidebarbg="skin6"></a></li>
                    </ul>
                    <!-- Logo BG -->
                </div>
            </div>
            <!-- End Tab 1 -->
        </div>
    </div>
</aside>

resources/views/superadmin/layouts/footer.blade.php
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center text-lg-left text-muted">
          &copy; 2019 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/license" class="nav-link" target="_blank">License</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>

resources/views/superadmin/layouts/sidebar.blade.php
@php
  $usr = Auth::guard('web')->user();
@endphp
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header d-flex align-items-center">
        <a class="navbar-brand" href="{{ route('admin.dashboard')}}">
          <img src="{{ asset('assetss/img/brand/tifa.png')}}" class="navbar-brand-img" alt="...">
        </a>
        <div class="ml-auto">
          <!-- Sidenav toggler -->
          <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          @if ($usr->can('dashboard.view'))
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {{ Request::routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard')}}"  >
                <i class="ni ni-shop text-primary"></i>
                <span class="nav-link-text">Dashboards</span>
              </a>
            </li>
          </ul>
          
            <hr class="my-3">
            @endif
            <!-- Heading -->
          @if ($usr->can('user.create') || $usr->can('user.view') ||  $usr->can('user.edit') ||  $usr->can('user.delete'))
          <h6 class="navbar-heading p-0 text-muted">User Action</h6>
          @endif
          <ul class="navbar-nav">
            @if ($usr->can('user.create') || $usr->can('user.view') ||  $usr->can('user.edit') ||  $usr->can('user.delete'))
            <li class="nav-item">
              <a class="nav-link {{ Request::routeIs('users.index') || Request::routeIs('users.create')  ? 'active' : '' }}" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-examples">
                <i class="ni ni-single-02 text-orange"></i>
                <span class="nav-link-text">User Manajement</span>
              </a>
              <div class="collapse" id="navbar-examples">
                <ul class="nav nav-sm flex-column">
                  @if ($usr->can('user.view'))
                  <li class="nav-item {{ Request::routeIs('users.index') ? 'active' : '' }}">
                    <a href="{{route('users.index')}}" class="nav-link">Manage Users</a>
                  </li>
                  @endif
                  @if($usr->can('user.create'))
                  <li class="nav-item {{ Request::routeIs('users.create') ? 'active' : '' }}">
                    <a href="{{ route('users.create')}}" class="nav-link">Create User</a>
                  </li>
                  @endif
                </ul>
              </div>
            </li>
            @endif
            @if ($usr->can('role.create') || $usr->can('role.view') ||  $usr->can('role.edit') ||  $usr->can('role.delete'))
              <li class="nav-item">
                <a class="nav-link {{ Request::routeIs('roles.index') || Request::routeIs('roles.create') || Request::routeIs('roles.edit') ? 'active' : '' }}" href="#navbar-components" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-components">
                  <i class="ni ni-atom text-info"></i>
                  <span class="nav-link-text">Roles & Permissions</span>
                </a>
                @if ($usr->can('role.view'))
                <div class="collapse" id="navbar-components">
                  <ul class="nav nav-sm flex-column">
                    <li class="nav-item">
                      <a href="{{ route('roles.index')}}" class="nav-link">All Roles</a>
                    </li>
                  </ul>
                </div>
                @endif
                @if ($usr->can('role.create'))
                <div class="collapse" id="navbar-components">
                  <ul class="nav nav-sm flex-column">
                    <li class="nav-item">
                      <a href="{{ route('roles.create')}}" class="nav-link">Create Roles</a>
                    </li>
                  </ul>
                </div>
                @endif
              </li>
            @endif
            @if ($usr->can('landing.create') || $usr->can('landing.view') ||  $usr->can('landing.edit') ||  $usr->can('landing.delete'))
            <li class="nav-item">
              <a class="nav-link" href="#navbar-landing" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-landing">
                <i class="ni ni-single-copy-04 text-pink"></i>
                <span class="nav-link-text">Landing Page</span>
              </a>
              <div class="collapse" id="navbar-landing">
                <ul class="nav nav-sm flex-column">
                  <li class="nav-item">
                    <a href="{{ route('sliders.index')}}" class="nav-link" >Slider Background</a>
                  </li>
                </ul>
              </div>
            </li>
            @endif
            @if ($usr->can('pengurus.create') || $usr->can('pengurus.view') ||  $usr->can('pengurus.edit') ||  $usr->can('pengurus.delete'))
            <li class="nav-item">
              <a class="nav-link" href="#navbar-tentang" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-tentang">
                <i class="ni ni-align-left-2 text-default"></i>
                <span class="nav-link-text">Tentang Himatifa</span>
              </a>
              <div class="collapse" id="navbar-tentang">
                <ul class="nav nav-sm flex-column">
                  <li class="nav-item">
                    <a href="#navbar-pengurus" class="nav-link" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-pengurus">Manajement Pengurus</a>
                    <div class="collapse show" id="navbar-pengurus" style="">
                      <ul class="nav nav-sm flex-column">
                        <li class="nav-item">
                          <a href="{{ route('bph.index')}}" class="nav-link ">BPH</a>
                        </li>
                        <li class="nav-item">
                          <a href="{{ route('anggota.index') }}" class="nav-link ">Anggota Departemen</a>
                        </li>
                        <li class="nav-item">
                          <a href="{{ route('visimisi.index') }}" class="nav-link ">Visi & Misi</a>
                        </li>
                      </ul>
                    </div>
                  </li>
                </ul>
              </div>
            </li>
            @endif
            @if ($usr->can('gallery.create') || $usr->can('gallery.view') ||  $usr->can('gallery.edit') ||  $usr->can('gallery.delete'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('gallery.index')}}">
                <i class="ni ni-archive-2 text-green"></i>
                <span class="nav-link-text">Gallery</span>
              </a>
            </li>
            @endif
            @if ($usr->can('contactus.create') || $usr->can('contactus.view') ||  $usr->can('contactus.edit') ||  $usr->can('contactus.delete'))
            <li class="nav-item">
              <a class="nav-link" href="#navbar-maps" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-maps">
                <i class="ni ni-map-big text-primary"></i>
                <span class="nav-link-text">Contact Us</span>
              </a>
              <div class="collapse" id="navbar-maps">
                <ul class="nav nav-sm flex-column">
                  <li class="nav-item">
                    <a href="{{ route('contact-us-admin.index')}}" class="nav-link">Pendaftaran Hima</a>
                  </li>
                  <li class="nav-item">
                    <a href="{{ route('contact-us-admin.create')}}" class="nav-link">Kritik & Saran</a>
                  </li>
                </ul>
              </div>
            </li>
            @endif
            @if ($usr->can('berita.create') || $usr->can('berita.view') ||  $usr->can('berita.edit') ||  $usr->can('berita.delete'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('manage-berita.index')}}">
                <i class="ni ni-single-copy-04 text-info"></i>
                <span class="nav-link-text">Berita</span>
              </a>
            </li>
            @endif
            @if ($usr->can('calendar.create') || $usr->can('calendar.view') ||  $usr->can('calendar.edit') ||  $usr->can('calendar.delete'))
            <li class="nav-item">
              <a class="nav-link" href="{{route('manage-calendar.index')}}">
                <i class="ni ni-calendar-grid-58 text-red"></i>
                <span class="nav-link-text">Calendar</span>
              </a>
            </li>
            <hr class="my-3">
            @endif
          </ul>
          <!-- Divider -->
          
          <!-- Heading -->
          
          <!-- Navigation -->
          <ul class="navbar-nav mb-md-3">
            @if ($usr->can('proposal.create') || $usr->can('proposal.view') ||  $usr->can('proposal.edit') ||  $usr->can('proposal.delete'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('proposal.indexhima')}}">
                <i class="ni ni-spaceship text-blue"></i>
                <span class="nav-link-text">Ajuan Proposal Kegiatan</span>
              </a>
            </li>
            @endif
            @if ($usr->can('proposal.editprodi'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('proposal.indexprodi')}}">
                <i class="ni ni-ui-04 text-green"></i>
                <span class="nav-link-text">Menu Prodi</span>
              </a>
            </li>
            @endif
            @if ($usr->can('proposal.editfakultas'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('proposal.indexfakultas')}}">
                <i class="ni ni-chart-pie-35 text-orange"></i>
                <span class="nav-link-text">Menu Fakultas</span>
              </a>
            </li>
            @endif
            @if ($usr->can('proposal.edithima'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('tipografi.index')}}">
                <i class="ni ni-palette text-danger"></i>
                <span class="nav-link-text">Deteksi Kesalahan Ketik</span>
              </a>
            </li>
            @endif
          </ul>
        </div>
      </div>
    </div>
  </nav>