routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Frontend\LandingsController::class, 'index'])->name('landing.home');
Route::get('/pengurus', [App\Http\Controllers\Frontend\PengurusController::class, 'index'])->name('pengurus.index');

//PROKER
Route::get('/program-kerja/{departemen}', [App\Http\Controllers\Frontend\ProgramKerjasController::class, 'index'])->name('proker.index');

//GALLERY
Route::get('/gallery-himatifa', [App\Http\Controllers\Frontend\GalleryController::class, 'index'])->name('galleryhima.index');

//? CALENDAR
Route::get('/calendar-himatifa', [App\Http\Controllers\Frontend\CalendarHimaController::class, 'index'])->name('calendarhima.index');

//* BERITA
Route::get('/berita-himatifa', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'index'])->name('beritahima.index');
Route::get('/berita-himatifa/{category}', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'showkategori'])->name('kategori.beritahima');
Route::get('/berita-himatifa/detail/{slug}', [App\Http\Controllers\Frontend\BeritaHimatifaController::class, 'show'])->name('beritahima.show');

//!CONTACT US
Route::get('/contact-us/deteksi-kesalahan-ketik', [App\Http\Controllers\ContactusController::class, 'pendaftaran'])->name('pendaftaran.hima');
Route::post('/contact-us/deteksi-kesalahan-ketik/hasil', [App\Http\Controllers\ContactusController::class, 'jarowinkler'])->name('jaro.distance.hima');
Route::post('/contact-us/deteksi-kesalahan-ketik/pdf-text', [App\Http\Controllers\ContactusController::class, 'pdftext'])->name('pdf-text.store');
Route::post('/contact-us/kritik-saran/store', [App\Http\Controllers\ContactusController::class, 'store_kritiksaran'])->name('kritiksaran.store');

Auth::routes();


Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('admin.dashboard');
    Route::resource('roles', App\Http\Controllers\Backend\RolesController::class);
    Route::get('/update-profile', [App\Http\Controllers\Backend\UpdateProfileController::class, 'index'])->name('update-profile.index');
    Route::post('/update-profile/update', [App\Http\Controllers\Backend\UpdateProfileController::class, 'update'])->name('update-profile.update');
    Route::resource('users', App\Http\Controllers\Backend\UsersController::class);
    Route::resource('sliders', App\Http\Controllers\Backend\SlidersController::class);

    // Pengurus
    Route::resource('pengurus/visimisi', App\Http\Controllers\Backend\Anggota\VisimisiController::class);

    // KAHIMA WAKAHIMA
    Route::get('/pengurus/bph', [App\Http\Controllers\Backend\Anggota\BphController::class, 'index'])->name('bph.index');
    Route::get('/pengurus/bph/create', [App\Http\Controllers\Backend\Anggota\BphController::class, 'create'])->name('bph.create');
    Route::post('/pengurus/bph/store', [App\Http\Controllers\Backend\Anggota\BphController::class, 'store'])->name('bph.store');
    Route::get('/pengurus/bph/edit/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'edit'])->name('bph.edit');
    Route::post('/pengurus/bph/update/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'update'])->name('bph.update');
    Route::delete('/pengurus/bph/delete/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'destroy'])->name('bph.destroy');

    // SEKRETARIS BENDAHARA
    Route::get('/pengurus/bph/createsb', [App\Http\Controllers\Backend\Anggota\BphController::class, 'createsb'])->name('bph.createsb');
    Route::post('/pengurus/bph/storesb', [App\Http\Controllers\Backend\Anggota\BphController::class, 'storesb'])->name('bph.storesb');
    Route::get('/pengurus/bph/editsb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'editsb'])->name('bph.editsb');
    Route::post('/pengurus/bph/updatesb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'updatesb'])->name('bph.updatesb');
    Route::delete('/pengurus/bph/deletesb/{id}', [App\Http\Controllers\Backend\Anggota\BphController::class, 'destroysb'])->name('bph.destroysb');

    // ANGGOTA
    Route::resource('pengurus/anggota', App\Http\Controllers\Backend\Anggota\AnggotaController::class);
    Route::resource('pengurus/departemen', App\Http\Controllers\Backend\Anggota\DepartemenController::class);

    Route::resource('pengurus/deskbph', App\Http\Controllers\Backend\Anggota\DeskripsiBPHController::class);
    Route::resource('pengurus/deskanggota', App\Http\Controllers\Backend\Anggota\DeskripsiAnggotaController::class);

    //Gallery
    Route::get('/gallery', [App\Http\Controllers\Backend\GallerysController::class, 'index'])->name('gallery.index');
    Route::get('/gallery/create', [App\Http\Controllers\Backend\GallerysController::class, 'create'])->name('gallery.create');
    Route::post('/gallery/store', [App\Http\Controllers\Backend\GallerysController::class, 'store'])->name('gallery.store');
    Route::get('/gallery/edit/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'edit'])->name('gallery.edit');
    Route::post('/gallery/update/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'update'])->name('gallery.update');
    Route::delete('/gallery/delete/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'destroy'])->name('gallery.destroy');

    Route::get('/category/create', [App\Http\Controllers\Backend\GallerysController::class, 'createcat'])->name('category.create');
    Route::post('/category/store', [App\Http\Controllers\Backend\GallerysController::class, 'storecat'])->name('category.store');
    Route::get('/category/edit/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'editcat'])->name('category.edit');
    Route::post('/category/update/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'updatecat'])->name('category.update');
    Route::delete('/category/delete/{id}', [App\Http\Controllers\Backend\GallerysController::class, 'destroycat'])->name('category.destroy');


    //Calendar
    Route::resource('calendar/manage-calendar', App\Http\Controllers\Backend\CalendarsController::class);

    //!BERITA
    Route::get('/berita/manage-berita', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'index'])->name('manage-berita.index');
    Route::get('/berita/manage-berita/create', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'create'])->name('manage-berita.create');
    Route::post('/berita/manage-berita/store', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'store'])->name('manage-berita.store');
    Route::get('/berita/manage-berita/edit/{slug}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'edit'])->name('manage-berita.edit');
    Route::post('/berita/manage-berita/update/{id}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'update'])->name('manage-berita.update');
    Route::delete('/berita/manage-berita/destroy/{id}', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'destroy'])->name('manage-berita.destroy');
    Route::get('/berita/manage-berita/slug', [App\Http\Controllers\Backend\Berita\BeritasController::class, 'slug'])->name('manage-berita.check-slug');


    Route::resource('berita/category-berita', App\Http\Controllers\Backend\Berita\CategoryBeritasController::class);

    //*CONTACT US
    Route::resource('/contact-us-admin', App\Http\Controllers\Backend\ContactUsAdminController::class);

    //! POPOSAL KEGIATAN
    Route::get('/ajuan-proposal-kegiatan', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexhima'])->name('proposal.indexhima');
    Route::get('/ajuan-proposal-kegiatan/prodi', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexprodi'])->name('proposal.indexprodi');
    Route::delete('/ajuan-proposal-kegiatan/destroy/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'destroy'])->name('proposal.destroy');
    Route::get('/ajuan-proposal-kegiatan/fakultas', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'indexfakultas'])->name('proposal.indexfakultas');
    Route::get('/ajuan-proposal-kegiatan/editprodi/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'editprodi'])->name('proposal.editprodi');
    Route::get('/ajuan-proposal-kegiatan/editfakultas/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'editfakultas'])->name('proposal.editfakultas');
    Route::post('/ajuan-proposal-kegiatan/updateprodi/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'updateprodi'])->name('proposal.updateprodi');
    Route::post('/ajuan-proposal-kegiatan/updatefakultas/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'updatefakultas'])->name('proposal.updatefakultas');
    Route::post('/ajuan-proposal-kegiatan/store-proposal', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'store'])->name('proposal.store');
    Route::get('/ajuan-proposal-kegiatan/{id}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'show'])->name('proposal.show');
    Route::get('/download-proposal-kegiatan/{file_name}', [App\Http\Controllers\Backend\Proposal\ProposalController::class, 'downloadprop'])->name('proposal.download');

    //? Deteksi KESALAHAN KETIK
    Route::get('/deteksi-kesalahan-ketik', [App\Http\Controllers\Backend\TipografiCheckController::class, 'index'])->name('tipografi.index');

app/Models/Anggota/Departemen.php
<?php

namespace App\Models\Anggota;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Departemen extends Model
{
    use HasFactory;
    protected $table = "departemen";
    protected $fillable = [
        'name', 'slug'
    ];
}

app/Http/Controllers/Backend/Anggota/DepartemenController.php
<?php

namespace App\Http\Controllers\Backend\Anggota;

use App\Http\Controllers\Controller;
use App\Models\Anggota\Departemen;
use Illuminate\Http\Request;

class DepartemenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('superadmin.backend.pengurus.departemen.departemen.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'name' => 'required|unique:departemen,name',
            'jabatan' => 'required',
        ]);

        $departemen = new Departemen;
        $departemen->departemen = $request->departemen;
        $departemen->slug = $request->slug;

        $departemen->save();

        return redirect()->route('anggota.index')->withSuccess('Departemen Berhasil Dibuat !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $departemen = Departemen::find($id);
        return view('superadmin.backend.pengurus.departemen.departemen.edit', compact('departemen'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $edit = Departemen::find($id);
        $request->validate([

            'departemen' => 'required',
            'slug' => 'required',
        ]);

        $departemen = [
            'departemen'      => $request['departemen'],
            'slug'      => $request['slug'],
        ];


        $edit->update($departemen);

        session()->flash('success', 'Departemen has been edited !!');
        return redirect()->route('anggota.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Departemen::find($id)->delete();
        return back()->withSuccess('Departemen Berhasil Dihapus !');
    }
}

resources/views/superadmin/backend/pengurus/departemen/departemen/create.blade.php
@extends('superadmin.layouts.master')
@section('tittle', 'Create Deskripsi BPH')  
@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Tables</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Tables</a></li>
                <li class="breadcrumb-item active"><a href="#">Roles</a></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
            <a href="#" class="btn btn-sm btn-neutral">New</a>
            <a href="#" class="btn btn-sm btn-neutral">Filters</a>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="container-fluid mt--6">
    <div class="row justify-content-center">
        <div class="col-lg-8 card-wrapper">
          <div class="card">
              <!-- Card header -->
              <div class="card-header">
                <h3 class="mb-0 text-center">Add Jabatan ANggota</h3>
              </div>
              <!-- Card body -->
              <div class="card-body">
                  <form action="{{ route('departemen.store')}}" method="POST">
                      @csrf
                      <div class="form-group">
                      <label class="form-control-label" for="departemen">Name</label>
                          <input type="text" class="form-control" id="departemen" placeholder="Enter Name" name="departemen" value="{{ old('departemen') }}">
                      </div>
                      @error('name')
                          <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              <span class="alert-icon"><i class="ni ni-fat-remove"></i></span>
                              <span class="alert-text"><strong>Error !</strong> {{$message}}</span>
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                      @enderror
                      <div class="form-group">
                        <label class="form-control-label" for="slug">Slug</label>
                            <input type="text" class="form-control" id="slug" placeholder="Enter Slug" name="slug" value="{{ old('slug') }}" readonly>
                        </div>
                        @error('slug')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <span class="alert-icon"><i class="ni ni-fat-remove"></i></span>
                                <span class="alert-text"><strong>Error !</strong> {{$message}}</span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror
                <div class="text-right">
                  <a type="button" class="btn btn-secondary" href="{{ route('anggota.index') }}">Back</a>
                  <button type="submit" class="btn btn-success"  value="create"><i class="ti-save"></i> Save</button>
                </div>
              </form>
            </div>
        </div>
      </div>
</div>
<script>
  $('#departemen').change(function(e) {
    $.get('{{ route('check-slug.departemen') }}', 
      { 'departemen': $(this).val() }, 
      function( data ) {
        $('#slug').val(data.slug);
      }
    );
  });
</script>

@endsection

resources/views/superadmin/backend/pengurus/departemen/departemen/edit.blade.php
@extends('superadmin.layouts.master')
@section('tittle', 'Edit Deskripsi BPH')  
@section('content')
<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Tables</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Tables</a></li>
                <li class="breadcrumb-item active"><a href="#">Roles</a></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
            <a href="#" class="btn btn-sm btn-neutral">New</a>
            <a href="#" class="btn btn-sm btn-neutral">Filters</a>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="container-fluid mt--6">
    <div class="row justify-content-center">
        <div class="col-lg-8 card-wrapper">
          <div class="card">
              <!-- Card header -->
              <div class="card-header">
                <h3 class="mb-0 text-center">Edit Departemen</h3>
              </div>
              <!-- Card body -->
              <div class="card-body">
                  <form action="{{ route('departemen.update', $departemen->id )}}" method="POST" >
                    @method('PUT')
                    @csrf
                      <div class="form-group">
                      <label class="form-control-label" for="departemen">Name</label>
                          <input type="text" class="form-control" id="departemen" placeholder="Enter Name" name="departemen" value="{{ $departemen->departemen }}">
                      </div>
                      @error('departemen')
                          <div class="alert alert-danger alert-dismissible fade show" role="alert">
                              <span class="alert-icon"><i class="ni ni-fat-remove"></i></span>
                              <span class="alert-text"><strong>Error !</strong> {{$message}}</span>
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                      @enderror
                      <div class="form-group">
                        <label class="form-control-label" for="slug">Slug</label>
                            <input type="text" class="form-control" id="slug" placeholder="Enter Slug" name="slug" value="{{ $departemen->slug }}" readonly>
                        </div>
                        @error('slug')
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <span class="alert-icon"><i class="ni ni-fat-remove"></i></span>
                                <span class="alert-text"><strong>Error !</strong> {{$message}}</span>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @enderror
              <div class="text-right">
                  <a type="button" class="btn btn-secondary" href="{{ route('anggota.index') }}">Back</a>
                  <button type="submit" class="btn btn-success"  value="create"><i class="ti-save"></i> Save</button>
              </div>
              </form>
            </div>
            </div>
        </div>
      </div>
</div>
<script>
    $('#departemen').change(function(e) {
      $.get('{{ route('check-slug.departemen') }}', 
        { 'departemen': $(this).val() }, 
        function( data ) {
          $('#slug').val(data.slug);
        }
      );
    });
</script>
@endsection